### ISSUE TITLE
test_all.py error

### ISSUE THREAD

**Issue by icsaas** [shayne-fletcher/ppf3#1]
after installation,when i type python test.py --verbose,it emerges errors follows,
Traceback (most recent call last):
  File "/home/sn0w/Projects/sandbox/lib/python2.7/site-packages/ppf/test/test_lattice_pricer.py", line 177, in deep_out_the_money_test
    fixed_leg = _create_fixed_leg(1.0)
  File "/home/sn0w/Projects/sandbox/lib/python2.7/site-packages/ppf/test/test_lattice_pricer.py", line 84, in _create_fixed_leg
    , ppf.pricer.payoffs.fixed_leg_payoff())
AttributeError: 'module' object has no attribute 'pricer'.

any ideas about the question?

**Comment by shayne-fletcher** [comment]
On Sun, Jun 8, 2014 at 12:07 AM, neros notifications@github.com wrote:

> any ideas about the question?

​Where did the code come from? If it's the ppf3 project on github, that's a
work in progress. It's not finished and it won't be compatible with Python
2.7. This might be of use to you by the way
http://shayne-fletcher.blogspot.com/2014/03/financial-modeling-in-python-windows-7.html.
​

## 

Shayne Fletcher

**Comment by icsaas** [comment]
It is the ppf3 project code.
when I  compile the source on Ubuntu, it emerges the error ,so i   change
some code in the test package (**init**.py and so on )  to make it correct
on Ubuntu,then i push the merge request.
could you tell me the difference between the ppf3 and ppf(the book's code),
actually,the book is really a greate wonderful book.I am reading and
learning .Thank you!

2014-06-08 21:49 GMT+08:00 Shayne Fletcher notifications@github.com:

**Comment by shayne-fletcher** [comment]
On Sun, Jun 8, 2014 at 12:46 PM, neros notifications@github.com wrote:

> could you tell me the difference between the ppf3 and ppf(the book's
> code),

​Yes, the code in ppf3 is based on ppf - it's being modified to work with
​the Python 3.0 family of interpreters but it's not finished. That's why
there are modules commented out in the initialization files. Do you have
access to the ppf code that accompanied the book? That will work with your
Python 2.7 interpreter with less effort. If not, check out
https://github.com/shayne-fletcher/zen (you'll find the original project
under zen/ppf/).

> actually,the book is really a greate wonderful book.I am reading and
> learning .Thank you!

​I'm very pleased to hear that. You're welcome!

## 

Shayne Fletcher
